-- Qlik Sales Analysis → Snowflake landing
-- Schema:  QUICKSTARTS.QLIK_SALES_ANALYSIS
-- Sources: s3://sigma-quickstarts-main/qlik/{DIM_CUSTOMER,DIM_PRODUCT,FACT_SALES}.csv

CREATE SCHEMA IF NOT EXISTS QUICKSTARTS.QLIK_SALES_ANALYSIS;
USE SCHEMA QUICKSTARTS.QLIK_SALES_ANALYSIS;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_NUMBER NUMBER(38,0),
  CUSTOMER        VARCHAR,
  CUSTOMER_TYPE   VARCHAR,
  SEGMENT_DESC    VARCHAR,
  REGION          VARCHAR
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
  LINE_DESC_1            VARCHAR,
  PRODUCT_GROUP_DESC     VARCHAR,
  PRODUCT_SUB_GROUP_DESC VARCHAR,
  PRODUCT_TYPE_DESC      VARCHAR
);

CREATE OR REPLACE TABLE FACT_SALES (
  ORDER_NUMBER    NUMBER(38,0),
  CUSTOMER_NUMBER NUMBER(38,0),
  LINE_DESC_1     VARCHAR,
  SALES_REP_NAME  VARCHAR,
  YYYYMM          VARCHAR(7),
  FISCAL_YEAR     NUMBER(4,0),
  FISCAL_MONTH    VARCHAR(3),
  ORDER_STATUS    VARCHAR,
  QUANTITY        NUMBER(38,0),
  REVENUE         NUMBER(38,15),
  COST            NUMBER(38,15)
);

CREATE OR REPLACE STAGE QUICKSTARTS.QLIK_SALES_ANALYSIS.S3_QLIK_STAGE
  URL = 's3://sigma-quickstarts-main/qlik/'
  FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', '-', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE
  );

COPY INTO DIM_CUSTOMER FROM @S3_QLIK_STAGE/DIM_CUSTOMER.csv ON_ERROR = ABORT_STATEMENT;
COPY INTO DIM_PRODUCT  FROM @S3_QLIK_STAGE/DIM_PRODUCT.csv  ON_ERROR = ABORT_STATEMENT;
COPY INTO FACT_SALES   FROM @S3_QLIK_STAGE/FACT_SALES.csv   ON_ERROR = ABORT_STATEMENT;

GRANT USAGE  ON DATABASE QUICKSTARTS                              TO ROLE SIGMA_SERVICE_ROLE;
GRANT USAGE  ON SCHEMA   QUICKSTARTS.QLIK_SALES_ANALYSIS          TO ROLE SIGMA_SERVICE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA QUICKSTARTS.QLIK_SALES_ANALYSIS    TO ROLE SIGMA_SERVICE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QUICKSTARTS.QLIK_SALES_ANALYSIS TO ROLE SIGMA_SERVICE_ROLE;

-- Quick verify
SELECT 'DIM_CUSTOMER' AS T, COUNT(*) AS ROWS FROM DIM_CUSTOMER
UNION ALL SELECT 'DIM_PRODUCT', COUNT(*) FROM DIM_PRODUCT
UNION ALL SELECT 'FACT_SALES',  COUNT(*) FROM FACT_SALES;
-- Expected: DIM_CUSTOMER=136, DIM_PRODUCT=852, FACT_SALES=55797
